<?php // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
header('Content-type: text/html');
header('Access-Control-Allow-Origin: * ');
header("Access-Control-Allow-Credentials: true");
header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
header('Access-Control-Max-Age: 1000');
header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');
$ch = curl_init();
$key21='I4T5iL9rOGJhyUnZCCWSTJbwylRLc0WO';
$key32='eYhpsB9hyX1CuhpyxNmEFe74o5qMzbEk';
$key2='7097847394897fea975b5975d053446c';
$key1='98yGhSsWj09ZvId3OoKtNUeSrbLVbT2M';
curl_setopt($ch, CURLOPT_URL, "https://api.authy.com/protected/json/phones/verification/start");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "api_key=".$key2."&via=sms&phone_number=".$_GET["phone"]."&country_code=".$_GET['countrycode']);

/*curl_setopt($ch, CURLOPT_POSTFIELDS, "api_key=98yGhSsWj09ZvId3OoKtNUeSrbLVbT2M&via=sms&phone_number=8981483911&country_code=91");*/
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = "Content-Type: application/x-www-form-urlencoded";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);
print_r($result);


?>